# Stage 1: Build FE
FROM node:20 AS builder 
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .  
RUN rm -rf node_modules package-lock.json && npm install && npm run build

# Stage 2: Nginx phục vụ FE
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
